baseURL: "https://iccg-2019.netlify.com/"
footnoteReturnLinkContents: ↩
permalinks:
  blog: /:title/
title: ICCG 2019
buildDrafts: false
canonifyURLs: false
disableKinds: 
  - taxonomy
  - taxonomyTerm
params:
  description: "Conflict, War and Uneven Development: De- and Re-constructions of space"
  longtitle: "8th International Conference of Critical Geography 2019"
