backend:
  name: git-gateway
media_folder: "static/images"
public_folder: "/images" 
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
  - name: "field-trips" # Used in routes, e.g., /admin/collections/blog
    label: "Field Trips" # Used in the UI
    folder: "content/field-trips" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "eventdate", widget: "datetime"}
      - {label: "Participants", name: "participants", widget: "string"}
      - {label: "Place of Discussion", name: "location", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "fieldtrip"}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Congress Title", name: "congresstitle", widget: "string"}
          - {label: "Dates", name: "dates", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - label: "Call for Papers"
        name: "call-for-papers"
        file: "content/call-for-papers.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - label: "Political Statement"
        name: "political-statement"
        file: "content/political-statement.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - label: "Practical Info"
        name: "practical-info"
        file: "content/practical-info.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - label: "Programme"
        name: "programme"
        file: "content/programme.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - label: "Registration"
        name: "registration"
        file: "content/registration.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-two, quote, bulleted-list]}
          - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
